name: Deploy to Azure Function App & DB schema
on:
  push:
    branches: [ main ]
permissions:
  id-token: write   # required for OIDC
  contents: read
env:
  AZURE_FUNCTIONAPP_NAME: 'func-demo-3673'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt --target=".python_packages/lib/site-packages"
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '.'

  deploy-schema:
    needs: build-and-deploy
    runs-on: arc-runner-set
    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy schema
        run: |
          sqlcmd -S free-sql-mi-4798156.2cbf604f830e.database.windows.net,1433 -d master \
            -G --authentication-method=ActiveDirectoryDefault -C \
            -Q "SELECT @@VERSION"
